"""Inspect captured generated bytes, memory envelope, instructions and producer inputs."""
from pathlib import Path
import hashlib, json, re, subprocess, sys
stage = Path(sys.argv[1]).resolve()
logs = Path('/home/jack/zcash-threaded-logs')
sdk = Path('/home/jack/zcash-qualification-scratch/wasi-sdk-27.0-x86_64-linux')
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
provenance = json.loads((stage/'provenance.json').read_text())
for name, expected in provenance['artifacts'].items(): assert sha(stage/name)==expected
class Reader:
    def __init__(self,b): self.b,self.p=b,0
    def byte(self): value=self.b[self.p]; self.p+=1; return value
    def uint(self):
        value=shift=0
        while True:
            byte=self.byte(); value|=(byte&127)<<shift
            if byte<128: return value
            shift+=7; assert shift<36
    def take(self,n): value=self.b[self.p:self.p+n]; assert len(value)==n; self.p+=n; return value
    def string(self): return self.take(self.uint()).decode()
def inspect(path):
    data=path.read_bytes(); assert data[:8]==b'\0asm\1\0\0\0'; r=Reader(data[8:]); sections={}
    while r.p<len(r.b):
        key=r.byte(); payload=r.take(r.uint())
        if key: assert key not in sections; sections[key]=payload
    r=Reader(sections[2]); imports=[]
    for _ in range(r.uint()):
        module,name,kind=r.string(),r.string(),r.byte(); row=dict(module=module,name=name,kind=kind)
        if kind==0: row['type']=r.uint()
        elif kind==2:
            flags=r.uint(); row.update(flags=flags,initial=r.uint(),maximum=r.uint() if flags&1 else None)
        else: raise AssertionError(f'unexpected import kind {kind}')
        imports.append(row)
    assert r.p==len(r.b)
    memory=[i for i in imports if i['kind']==2]; assert len(memory)==1
    assert memory[0]['flags']==3 and memory[0]['maximum']==4096 and memory[0]['initial']>0
    assert 5 not in sections, 'must import sole memory'
    assert not any(i['module'].startswith('wasi') for i in imports)
    r=Reader(sections[7]); exports=[]
    for _ in range(r.uint()): exports.append(dict(name=r.string(),kind=r.byte(),index=r.uint()))
    output=logs/f'{stage.name}-{path.parent.name}-disassembly.log'
    argv=[str(sdk/'bin/llvm-objdump'),'-d',str(path)]
    with output.open('w') as f: subprocess.run(argv,check=True,stdout=f,timeout=60)
    text=output.read_text(); atomic=len(re.findall(r'\batomic\.|\.atomic\.',text)); waits=len(re.findall(r'memory\.atomic\.wait',text))
    assert atomic>0 and waits>0
    return dict(sha256=sha(path),imports=imports,exports=exports,atomic_instructions=atomic,wait_instructions=waits,
        disassembly=dict(argv=argv,path=str(output),sha256=sha(output)))
result=dict(raw=inspect(stage/'raw/threaded.wasm'),generated=inspect(stage/'web/qualification_bg.wasm'))
raw_names={e['name'] for e in result['raw']['exports']}
assert {'__wasm_init_tls','__tls_size','__tls_align','__tls_base'} <= raw_names
map_text=(stage/'raw/threaded.map').read_text()
paths=set(re.findall(r'(/[^\s():]+(?:adapter\.o|sqlite3\.o))',map_text))
assert len(paths)==1, paths
result['producer_objects']={p:sha(Path(p)) for p in paths}
archive,member = re.search(r'(/[^\s()]+\.rlib)\(([^()]+sqlite3\.o)\)',map_text).groups()
object_bytes = subprocess.check_output([str(sdk/'bin/llvm-ar'),'p',archive,member])
result['producer_objects'][archive+'('+member+')'] = hashlib.sha256(object_bytes).hexdigest()
result['threaded_libc']=dict(path=str(sdk/'share/wasi-sysroot/lib/wasm32-wasi-threads/libc.a'),sha256=sha(sdk/'share/wasi-sysroot/lib/wasm32-wasi-threads/libc.a'))
result['clang']=subprocess.check_output([str(sdk/'bin/clang'),'--version'],text=True)
result['source_provenance_sha256']=sha(stage/'provenance.json')
output=logs/f'{stage.name}-inspection.json'; output.write_text(json.dumps(result,indent=2)+'\n')
print(json.dumps(dict(output=str(output),generated_sha256=result['generated']['sha256'],memory=[i for i in result['generated']['imports'] if i['kind']==2],atomic=result['generated']['atomic_instructions'],waits=result['generated']['wait_instructions'],objects=result['producer_objects']),indent=2))
