"""Copy verified generated bytes and qualification consumers into a fresh bundle."""
from pathlib import Path
import hashlib, json, shutil, sys
ROOT = Path(__file__).resolve().parent
BASE = Path('/home/jack/zcash-generated-runtime-scratch/build-1789135187453484355')
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def package(destination, threaded=None):
    destination.mkdir()
    origins = {}
    for source, name in [(BASE,'baseline')] + ([(threaded,'threaded')] if threaded else []):
        provenance = json.loads((source / 'provenance.json').read_text())
        for path, expected in provenance['artifacts'].items():
            assert sha(source / path) == expected, f'changed producer input {path}'
        origins[name] = dict(stage=str(source), provenance_sha256=sha(source / 'provenance.json'))
        shutil.copytree(source / 'web', destination / name)
        host = ROOT.parent / 'runtime/runtime-host.mjs' if name == 'baseline' else ROOT / 'runtime-host.mjs'
        shutil.copyfile(host, destination / name / 'runtime-host.mjs')
        (destination / name / 'package.json').write_text('{"private":true,"type":"module"}\n')
    for p in ROOT.glob('*.mjs'):
        if not p.name.startswith(('test-', 'run-')): shutil.copyfile(p, destination / p.name)
    (destination / 'index.html').write_text('<!doctype html><meta charset="utf-8"><title>Threaded qualification</title>')
    manifest = dict(origins=origins, files={str(p.relative_to(destination)):dict(sha256=sha(p),bytes=p.stat().st_size) for p in destination.rglob('*') if p.is_file()})
    (destination / 'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
if __name__ == '__main__': package(Path(sys.argv[1]),Path(sys.argv[2]) if len(sys.argv)>2 else None)
