import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { pathToFileURL } from 'node:url';
import { parseNetworkParameters } from '../../dist/src/network-parameters.js';
import { cases, compare } from '../../tests/network-parameters/parity.mjs';
const [nativeObservations, web] = process.argv.slice(2);
const facts = JSON.parse(await readFile(new URL('../../tests/network-parameters/source-constants.json', import.meta.url)));
const all = cases();
const observations = JSON.parse(await readFile(nativeObservations));
console.log('native', compare(parseNetworkParameters, observations, facts));
const wasm = await import(pathToFileURL(`${web}/adapter.js`));
await wasm.default({ module_or_path: await readFile(`${web}/adapter_bg.wasm`) });
const wasmObservations = all.map(c => { try { return JSON.parse(wasm.observe(c.bytes, c.height)); } catch { return null; } });
assert.deepEqual(wasmObservations, observations);
console.log('Node WASM', compare(parseNetworkParameters, wasmObservations, facts));
