#!/usr/bin/env python3
"""Read-only stage audit and genuine generator reproduction into fresh own scratch."""
import hashlib,json,os,subprocess,sys,time,importlib.util
from pathlib import Path
sys.dont_write_bytecode=True
stage=Path(sys.argv[1]).resolve()
scratch=Path(os.environ['WD_SCRATCH']).resolve()
if stage.parent!=scratch: raise RuntimeError('stage outside owned scratch')
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def require(v,m):
    if not v: raise RuntimeError(m)
receipt=json.loads((stage/'provenance.json').read_text())
producer=json.loads((stage/'producer.json').read_text())
require(all(receipt.get(k)==v for k,v in producer.items()),'producer/provenance drift')
def inventory(root): return {str(p.relative_to(root)): {'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(root.rglob('*')) if p.is_file()}
for family in ['source','inputs']:
    require(inventory(stage/family)==receipt[family],f'{family} full inventory drift')
    for name,item in receipt[family].items():
        p=stage/family/name
        require(sha(p)==item['sha256'] and p.stat().st_size==item['bytes'],f'{family}/{name} drift')
spec=importlib.util.spec_from_file_location('producer_checks',Path(__file__).with_name('build.py'))
checks=importlib.util.module_from_spec(spec);spec.loader.exec_module(checks)
checks.check_inputs(Path(receipt['repository']),json.loads((stage/'source/inputs.json').read_text()),stage/'inputs')
require(inventory(stage/'bundle') | {f'raw/{k}':v for k,v in inventory(stage/'raw').items()} == receipt['artifacts'],'artifact full inventory drift')
for name,item in receipt['artifacts'].items():
    p=stage/name if name.startswith('raw/') else stage/'bundle'/name
    require(sha(p)==item['sha256'] and p.stat().st_size==item['bytes'],f'artifact drift {name}')
for name,key in [('runtime.map','map_sha256'),('features.txt','features_sha256'),('inspection.json','inspection_sha256'),('registry.json','registry_sha256'),('native.log','native_log_sha256'),('native-reference','native_binary_sha256')]:
    require(sha(stage/name)==receipt[key],f'{name} drift')
output=scratch/f'regenerated-{time.time_ns()}';output.mkdir()
tool=Path(receipt['tools']['bindgen']['command'][0])
require(sha(tool)==receipt['tools']['bindgen']['sha256'],'generator executable drift')
subprocess.run([str(tool),str(stage/'raw/issue_2_qualification.wasm'),'--target','web','--keep-lld-exports','--out-dir',str(output),'--out-name','storage'],check=True,timeout=60)
regenerated={}
for p in output.iterdir():
    require(p.read_bytes()==(stage/'bundle'/p.name).read_bytes(),f'generated bytes differ: {p.name}')
    regenerated[p.name]=sha(p)
registry=Path(receipt['environment']['CARGO_HOME'])/'registry/src/index.crates.io-1949cf8c6b5b557f'
repo=Path(receipt['environment']['WD_WALLET_REPO'])
revision='a9142ee100b3a563b7d9ba7a8e94201d00ad8154'
source_count=0
for package,folder in [('zakura-client-backend-0.1.0-rc4','zcash_client_backend'),('zakura-client-sqlite-0.1.0-rc4','zcash_client_sqlite'),('zakura-pczt-0.1.0-rc2','pczt')]:
    package_dir=registry/package
    require(package_dir.is_dir() and (package_dir/'src').is_dir(),f'wallet source directory missing: {package}')
    prefix=f'librustzcash/{folder}/'
    tree=subprocess.check_output(['git','-C',str(repo),'ls-tree','-r','--name-only','-z',revision,'--',prefix+'src/'])
    expected={Path(name.decode()).relative_to(prefix) for name in tree.split(b'\0') if name and name.endswith(b'.rs')}
    require(expected,f'wallet source inventory empty in Git pin: {package}')
    actual={p.relative_to(package_dir) for p in (package_dir/'src').rglob('*.rs') if p.is_file()}
    require(actual==expected,f'wallet source inventory differs from Git pin: {package}; missing={sorted(map(str,expected-actual))}; unexpected={sorted(map(str,actual-expected))}')
    for relative in sorted(expected):
        p=package_dir/relative
        pinned=subprocess.check_output(['git','-C',str(repo),'show',f'{revision}:librustzcash/{folder}/{relative}'])
        require(p.read_bytes()==pinned,f'wallet source differs from Git pin: {package}/{relative}')
        source_count+=1
sdk=Path(receipt['environment']['runtime_sdk'])
extras=[sdk/'share/wasi-sysroot/lib/wasm32-wasi/libc.a',sdk/'bin/llvm-objdump',registry/'libsqlite3-sys-0.35.0/sqlite3/sqlite3.c',registry/'libsqlite3-sys-0.35.0/sqlite3/sqlite3.h']
for name in ['rustc','cargo']:
    extras.append(Path(subprocess.check_output(['rustup','which',name],text=True).strip()))
require({str(p):sha(p) for p in extras}==receipt['additional_inputs'],'additional input identity drift')
verified=json.loads(subprocess.check_output([sys.executable,str(stage/'source/verify-inputs.py'),str(stage)],env={**os.environ,**receipt['environment']},text=True))
require(verified==json.loads((stage/'registry.json').read_text()),'registry recheck drift')
require(len(regenerated)==4,'generated asset inventory drift')
print(json.dumps({'pass':True,'stage':str(stage),'provenance_sha256':sha(stage/'provenance.json'),'regenerated_directory':str(output),'regenerated_byte_identical':regenerated,'wallet_git_source_files_checked':source_count,'additional_inputs':{str(p):sha(p) for p in extras},'build_logs':{p.name:sha(p) for p in stage.glob('*.log')}},indent=2))
