#!/usr/bin/env python3
"""Read-only stage audit and genuine generator reproduction into fresh own scratch."""
import hashlib,json,os,subprocess,sys,time
from pathlib import Path
stage=Path(sys.argv[1]).resolve()
scratch=Path('/home/jack/zcash-wallet-durability-scratch')
if stage.parent!=scratch: raise RuntimeError('stage outside owned scratch')
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def require(v,m):
    if not v: raise RuntimeError(m)
receipt=json.loads((stage/'provenance.json').read_text())
for family in ['source','inputs']:
    for name,item in receipt[family].items():
        p=stage/family/name
        require(sha(p)==item['sha256'] and p.stat().st_size==item['bytes'],f'{family}/{name} drift')
for name,item in receipt['artifacts'].items():
    p=stage/name if name.startswith('raw/') else stage/'bundle'/name
    require(sha(p)==item['sha256'] and p.stat().st_size==item['bytes'],f'artifact drift {name}')
for name,key in [('runtime.map','map_sha256'),('features.txt','features_sha256'),('inspection.json','inspection_sha256'),('registry.json','registry_sha256'),('native.log','native_log_sha256'),('native-reference','native_binary_sha256')]:
    require(sha(stage/name)==receipt[key],f'{name} drift')
output=scratch/f'regenerated-{time.time_ns()}';output.mkdir()
tool=Path('/home/jack/zcash-node-runtime-scratch/wasm-bindgen-0.2.128-x86_64-unknown-linux-musl/wasm-bindgen')
require(sha(tool)==receipt['tools']['bindgen']['sha256'],'generator executable drift')
subprocess.run([str(tool),str(stage/'raw/issue_2_qualification.wasm'),'--target','web','--keep-lld-exports','--out-dir',str(output),'--out-name','storage'],check=True,timeout=60)
regenerated={}
for p in output.iterdir():
    require(p.read_bytes()==(stage/'bundle'/p.name).read_bytes(),f'generated bytes differ: {p.name}')
    regenerated[p.name]=sha(p)
registry=scratch/'cargo/registry/src/index.crates.io-1949cf8c6b5b557f'
repo=Path('/home/jack/zcash-qualification-scratch/wallet')
revision='a9142ee100b3a563b7d9ba7a8e94201d00ad8154'
source_count=0
for package,folder in [('zakura-client-backend-0.1.0-rc4','zcash_client_backend'),('zakura-client-sqlite-0.1.0-rc4','zcash_client_sqlite'),('zakura-pczt-0.1.0-rc2','pczt')]:
    for p in (registry/package/'src').rglob('*.rs'):
        relative=p.relative_to(registry/package)
        pinned=subprocess.check_output(['git','-C',str(repo),'show',f'{revision}:librustzcash/{folder}/{relative}'])
        require(p.read_bytes()==pinned,f'wallet source differs from Git pin: {package}/{relative}')
        source_count+=1
sdk=Path('/home/jack/zcash-qualification-scratch/wasi-sdk-27.0-x86_64-linux')
extras=[sdk/'share/wasi-sysroot/lib/wasm32-wasi/libc.a',sdk/'bin/llvm-objdump',registry/'libsqlite3-sys-0.35.0/sqlite3/sqlite3.c',registry/'libsqlite3-sys-0.35.0/sqlite3/sqlite3.h']
for name in ['rustc','cargo']:
    extras.append(Path(subprocess.check_output(['rustup','which',name],text=True).strip()))
print(json.dumps({'pass':True,'stage':str(stage),'provenance_sha256':sha(stage/'provenance.json'),'regenerated_directory':str(output),'regenerated_byte_identical':regenerated,'wallet_git_source_files_checked':source_count,'additional_inputs':{str(p):sha(p) for p in extras},'build_logs':{p.name:sha(p) for p in stage.glob('*.log')}},indent=2))
