import assert from 'node:assert/strict';
import { isNativeQuota, fill, LIMIT } from './quota-pressure.mjs';
assert.equal(isNativeQuota({name:'QuotaExceededError'}),false);
assert.equal(isNativeQuota(Object.assign(Error('disk'),{code:'ENOSPC'})),false);
assert.equal(isNativeQuota(new DOMException('control only','QuotaExceededError')),true);
assert.equal(isNativeQuota(new DOMException('control only','UnknownError')),false);
// Offline controls only: these handles never qualify browser quota.
let size=0, largest=0;
const h={getSize:()=>size,write(b,{at}){largest=Math.max(largest,at+b.length);size=at+b.length;return b.length;},flush(){}};
await assert.rejects(fill(h),/64 MiB cap/);
assert.equal(size,LIMIT);assert.equal(largest,LIMIT);
size=0;
const full={...h,write(b,{at}){if(at+b.length>100001)throw new DOMException('control only','QuotaExceededError');size=at+b.length;return b.length;}};
const result=await fill(full);
assert.equal(result.bytes,100001);assert.equal(result.errors.at(-1).requested,1);
await assert.rejects(fill({...h,write(){throw Error('unrelated failure');}}),/unrelated failure/);
console.log('quota native-category, byte-cap, refinement and unexpected-error controls pass (not platform evidence)');
// Firefox stacks can omit both the exception name and message. No prototype patch.
const {errorDetails}=await import('./quota-pressure.mjs');
const original=new DOMException('original pressure failure','QuotaExceededError');
Object.defineProperty(original,'stack',{value:'write@worker.mjs:1:1'});
const serialized=JSON.parse(JSON.stringify(errorDetails(original)));
assert.equal(serialized.name,'QuotaExceededError');
assert.equal(serialized.message,'original pressure failure');
assert.equal(serialized.nativeCode,22);
assert.equal(serialized.stack,'write@worker.mjs:1:1');
assert.match(serialized.error,/QuotaExceededError: original pressure failure/);
const progress={};size=0;
await assert.rejects(fill(h,progress),/64 MiB cap/);
assert.equal(progress.bytes,LIMIT);
console.log('stack-only exception serialization and failure progress controls pass (not platform evidence)');
