import assert from 'node:assert/strict';
import { isNativeQuota, fill, LIMIT } from './quota-pressure.mjs';
assert.equal(isNativeQuota({name:'QuotaExceededError'}),false);
assert.equal(isNativeQuota(Object.assign(Error('disk'),{code:'ENOSPC'})),false);
assert.equal(isNativeQuota(new DOMException('control only','QuotaExceededError')),true);
assert.equal(isNativeQuota(new DOMException('control only','UnknownError')),false);
// Offline controls only: these handles never qualify browser quota.
let size=0, largest=0;
const h={getSize:()=>size,write(b,{at}){largest=Math.max(largest,at+b.length);size=at+b.length;return b.length;},flush(){}};
await assert.rejects(fill(h),/64 MiB cap/);
assert.equal(size,LIMIT);assert.equal(largest,LIMIT);
size=0;
const full={...h,write(b,{at}){if(at+b.length>100001)throw new DOMException('control only','QuotaExceededError');size=at+b.length;return b.length;}};
const result=await fill(full);
assert.equal(result.bytes,100001);assert.equal(result.errors.at(-1).requested,1);
await assert.rejects(fill({...h,write(){throw Error('unrelated failure');}}),/unrelated failure/);
console.log('quota native-category, byte-cap, refinement and unexpected-error controls pass (not platform evidence)');
// Firefox stacks can omit both the exception name and message. No prototype patch.
const {errorDetails}=await import('./quota-pressure.mjs');
const original=new DOMException('original pressure failure','QuotaExceededError');
Object.defineProperty(original,'stack',{value:'write@worker.mjs:1:1'});
const serialized=JSON.parse(JSON.stringify(errorDetails(original)));
assert.equal(serialized.name,'QuotaExceededError');
assert.equal(serialized.message,'original pressure failure');
assert.equal(serialized.nativeCode,22);
assert.equal(serialized.stack,'write@worker.mjs:1:1');
assert.match(serialized.error,/QuotaExceededError: original pressure failure/);
const progress={};size=0;
await assert.rejects(fill(h,progress),/64 MiB cap/);
assert.equal(progress.bytes,LIMIT);
console.log('stack-only exception serialization and failure progress controls pass (not platform evidence)');
// Real host 2 returned a short count; offline control reproduces that contract.
size=0;
const partial={...h,write(b,{at}){assert.equal(at,size);const n=Math.min(b.length,100001-size);size+=n;return n;},truncate(n){if(n>100001)throw new DOMException('control truncate limit','QuotaExceededError');size=n;}};
const short=await fill(partial);
assert.equal(short.bytes,100001);assert.equal(short.saturation,'zero-write');
assert.equal(short.errors.length,0); // Zero/short is not a native exception.
assert.equal(short.writes.reduce((sum,w)=>sum+w.returned,0),100001);
assert.ok(short.writes.some(w=>w.returned>0 && w.returned<w.requested));
assert.equal(short.writes.at(-1).requested,1);assert.equal(short.writes.at(-1).returned,0);
assert.equal(short.probe.op,'truncate');assert.equal(short.probe.requestedSize,100002);
assert.equal(short.probe.name,'QuotaExceededError');assert.equal(short.probe.nativeQuota,true);
await assert.rejects(fill({...h,write(){return -1;}}),/invalid filler write count/);
await assert.rejects(fill({...h,write(b){return b.length+1;}}),/invalid filler write count/);
console.log('short/zero counts and bounded native truncate-probe controls pass (not platform evidence)');
size=0;
const zero=await fill({...h,write(){return 0;},truncate(n){size=n;}});
assert.equal(zero.saturation,'zero-write');assert.equal(zero.bytes,1);
assert.equal(zero.errors.length,0);assert.equal(zero.probe.nativeQuota,undefined);
assert.equal(zero.probe.sizeAfter,1);
size=0;const tinyProgress={};
await assert.rejects(fill({...h,write(){size++;return 1;}},tinyProgress),/filler attempt limit/);
assert.equal(tinyProgress.writes.length,4096);assert.equal(size,4096);
console.log('successful truncate is not an exception; tiny-progress attempts bounded');
